In [1]:
import numpy as np
from scipy.sparse import csr_matrix, coo_matrix, triu, tril, hstack
from scipy.sparse.linalg import spsolve
import graphrelations as gr
from iterativemethods import *
from aggregation_coarsening import *
from multilevelmethod import *


In [2]:
testmat = np.zeros((8,8))
is_edge = [(1,5),(2,4), (2,8), (3,5),(4,2), (4,6), (5,1), (5,3), (5,6), (5,7), (6,4), (6,5), (6,8), (7,5), (8,2), (8,6)]
for i,j in is_edge:
    testmat[i-1,j-1] = 1
testmat = coo_matrix(testmat)
ev = gr.EV(testmat)
ee = gr.EE(ev)

In [3]:
testb = np.ones(testmat.shape[0])
x = B_TL_symmetric(testmat, b=testb ,c_factor=1.5, max_iter=100000)


A = Laplacian(testmat)

# make last row and column zeros to make it invertible, leave diagonal
# altering sparsity structure of csr, coo is expensive so ideally this will
# be updated someday to use a lil matrix or something else..
# must eliminate zeros or they stay in the nonzero data
A[A.shape[0] - 1, :-1] = 0
A[:-1, A.shape[0] - 1] = 0
A.eliminate_zeros()

xcompare = spsolve(A, testb)
print(x[0]-xcompare)
print(x[0])
print(xcompare)

[-2.69800387e-06  7.30799612e-08 -2.69800387e-06  1.46159922e-07
 -2.69800387e-06 -8.24563958e-07 -3.32248384e-06  0.00000000e+00]
[9.4999973  2.50000007 9.4999973  4.00000015 8.4999973  4.49999918
 9.49999668 0.5       ]
[9.5 2.5 9.5 4.  8.5 4.5 9.5 0.5]


D:\LinearAlgebra\multilevelmethods\venv\lib\site-packages\scipy\sparse\_index.py:146: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)


In [7]:
print(x)

(array([9.4999973 , 2.50000007, 9.4999973 , 4.00000015, 8.4999973 ,
       4.49999918, 9.49999668, 0.5       ]), 8, 3.547484117641209, 1.7451390701251666e-06)


In [8]:
from scipy.io import mmread

matrix = mmread('Graphs/cocktail.mtx')
with open('Graphs/cocktail_labels.txt') as file:
    labels = file.read().splitlines()

In [9]:
# this cocktail.mtx matrix is not an adjacency matrix but
# a relation of cocktails to ingredients
# getting the adjacency of ingredient to ingredient with
mat = matrix.T @ matrix

In [10]:
testb2 = np.zeros(mat.shape[0])
xTL = B_TL_symmetric(mat, b=testb2, c_factor = 4, max_iter=5000)
print(xTL)

(array([ 3.17201084e-07,  3.46862745e-07,  1.88710461e-07,  1.25355786e-07,
        1.20157350e-08,  4.64978651e-07,  2.99439533e-07,  2.23598662e-07,
        7.69873322e-07,  4.04432347e-07,  1.81149866e-06,  2.00772322e-06,
        9.70239632e-07,  2.23423541e-06,  2.62183868e-06,  3.33280589e-06,
        1.91021059e-06,  7.67324765e-08,  8.75832626e-08, -8.93734071e-07,
       -1.65268401e-10,  4.54943442e-07,  8.53312897e-08,  1.53270391e-07,
        5.48795893e-07,  2.57912962e-07,  4.38442323e-07,  9.40452099e-07,
        5.76782112e-07,  6.95364787e-07,  7.03066223e-08, -3.14846196e-07,
        1.19250935e-07, -7.96196943e-08,  5.37474713e-07,  1.21981533e-06,
        9.30264829e-07,  1.31187875e-06,  1.40939089e-07,  2.43317671e-07,
        2.30727564e-07,  2.76506251e-07,  4.23016883e-07,  5.71556173e-07,
        2.66980607e-07,  1.50149126e-07, -4.13695515e-08,  1.01201323e-06,
        1.20045905e-07,  2.09395593e-07,  3.49179011e-07,  3.47028713e-07,
        9.74847414e-07, 